package com.tastbudz.util;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;

import com.tastbudz.model.Coordinates;


public final class GeolocationUtil {
	private final static String ENCODING = "UTF-8";
	// This is a Google API Key, generated by a member of the UA Spring team, can be changed if needed
	private final static String KEY = "ABQIAAAAtibbxuabc4IbMMd3Lz6YKxT8h4OmK3OACxx2GTyIwybqxjarwRRNysxHsfcnzRtf9nk6CkJc3fb05Q";


	public static Coordinates getGeoLocation (String address) throws IOException {
		BufferedReader in = new BufferedReader (new InputStreamReader (new URL ("http://maps.google.com/maps/geo?q="+URLEncoder.encode (address, ENCODING)+"&output=csv&key="+KEY).openStream ()));
		String line;
		Coordinates location = null;
		int statusCode = -1;
		while ((line = in.readLine ()) != null) {
			// Format: 200,6,42.730070,-73.690570
			statusCode = Integer.parseInt (line.substring (0, 3));
			if (statusCode == 200) {
				String longitude = line.substring ("200,6,".length (), line.indexOf (',', "200,6,".length ()));
				String latitude = line.substring (line.indexOf (',', "200,6,".length ())+1, line.length ());
				
				location = new Coordinates();
				location.setLatitude(Double.parseDouble(latitude));
				location.setLongitude(Double.parseDouble(longitude));
			}
		}
		if (location == null) {
			switch (statusCode) {
			case 400: throw new IOException ("Bad Request");
			case 500: throw new IOException ("Unknown error from Google Encoder");
			case 601: throw new IOException ("Missing query");
			case 602: return null;
			case 603: throw new IOException ("Legal problem");
			case 604: throw new IOException ("No route");
			case 610: throw new IOException ("Bad key");
			case 620: throw new IOException ("Too many queries");
			}
		}
		return location;
	}
		
	public static void main(String[] args) {
		try {
			Coordinates c = GeolocationUtil.getGeoLocation("944 Natchez Ct, Walnut Creek CA 94598");
			System.out.println(c);
			c = GeolocationUtil.getGeoLocation("919 Bancroft Rd, Walnut Creek CA 94598");
			System.out.println(c);
			c = GeolocationUtil.getGeoLocation("11627 Calamar Ct, San Diego CA 92124");
			System.out.println(c);
		} 
		catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
